[package]
name = "miro"
version = "0.1.0"
description = "My Terminal Emulator"
authors = ["o2sh <ossama-hjaji@live.fr>"]
edition = "2018"
readme = "README.md"
license = "MIT"
repository = "https://github.com/o2sh/miro"

[dependencies]
bitflags = "1.0.1"
failure = "0.1.1"
gl = "0.14.0"
palette = "0.2.1"
serde = "1.0.27"
serde_derive = "1.0.27"
toml = "0.5.8"
harfbuzz-sys = "0.1.15"
libc = "0.2.86"
mio = "0.6.12"
unicode-width = "0.1.4"
egli = "0.5.0"
euclid = "0.22.1"
serde_json = "1.0"
regex = "1.3.4"
image = "0.23.13"
maplit = "1.0.1"
unicode-segmentation = "1.2.0"
vte = "0.3.2"
chrono = "0.4"
lazy_static = "1.4.0"
sysinfo = "0.16.4"
clap = "2.33.3"
clipboard = "0.5"
open = "1.2"

[target.'cfg(any(target_os = "android", all(unix, not(target_os = "macos"))))'.dependencies]
freetype = "0.3.0"
servo-fontconfig = "0.4.0"

[target.'cfg(target_os = "macos")'.dependencies]
core-text = "9.2.0"

[dependencies.glium]
default-features = false
version = "0.29.0"
features = ["glutin"]